/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convertunits;

/**
 *
 * @author Smktelkom
 */
public class numeral extends javax.swing.JFrame {
    private int i;
    private String hasil,a;

    /**
     * Creates new form ns
     */
    public numeral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pilihan2 = new javax.swing.JComboBox<>();
        pilihan1 = new javax.swing.JComboBox<>();
        output = new javax.swing.JTextField();
        input = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(169, 158, 136));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Make it FUN\\XI\\PBO\\SM2\\cal.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(290, 90, 120, 193);

        pilihan2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Binary", "Octal", "Decimal", "Hexadecimal" }));
        jPanel1.add(pilihan2);
        pilihan2.setBounds(170, 90, 110, 30);

        pilihan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Binary", "Octal", "Decimal", "Hexadecimal" }));
        jPanel1.add(pilihan1);
        pilihan1.setBounds(10, 90, 110, 30);

        output.setEditable(false);
        jPanel1.add(output);
        output.setBounds(170, 110, 110, 40);
        jPanel1.add(input);
        input.setBounds(10, 110, 110, 40);

        jButton1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/D:/Make it FUN/XI/PBO/SM2/small.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(90, 180, 110, 40);

        jPanel2.setBackground(new java.awt.Color(244, 192, 66));
        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(122, 96, 33));
        jLabel2.setText("Numeral Systems");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(100, 20, 210, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 420, 70);

        jButton2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/D:/Make it FUN/XI/PBO/SM2/ba.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(90, 240, 110, 40);

        jLabel4.setFont(new java.awt.Font("Arrow Crafter", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("-----^");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 110, 40, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 300);

        setSize(new java.awt.Dimension(436, 341));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(pilihan1.getSelectedItem().equals("Binary")){

            if(pilihan2.getSelectedItem().equals("Binary")){
                a = (input.getText());
                hasil = a;

            }else if(pilihan2.getSelectedItem().equals("Decimal")){
                i = Integer.parseInt(input.getText(),2);
                hasil = String.format("%d",i);

            }else if(pilihan2.getSelectedItem().equals("Hexadecimal")){
                i = Integer.parseInt(input.getText(),2);
                hasil = Integer.toHexString(i);

            }else if(pilihan2.getSelectedItem().equals("Octal")){
                i = Integer.parseInt(input.getText(),2);
                hasil = Integer.toOctalString(i);

            }

        }else if(pilihan1.getSelectedItem().equals("Decimal")){

            if(pilihan2.getSelectedItem().equals("Binary")){
                i = Integer.parseInt(input.getText());
                hasil = Integer.toBinaryString(i);

            }else if(pilihan2.getSelectedItem().equals("Decimal")){
                a = (input.getText());
                hasil = a;

            }else if(pilihan2.getSelectedItem().equals("Hexadecimal")){
                i = Integer.parseInt(input.getText());
                hasil = Integer.toHexString(i);

            }else if(pilihan2.getSelectedItem().equals("Octal")){
                i = Integer.parseInt(input.getText());
                hasil = Integer.toOctalString(i);
            }

        }else if(pilihan1.getSelectedItem().equals("Hexadecimal")){

            if(pilihan2.getSelectedItem().equals("Binary")){
                i = Integer.parseInt(input.getText(),16);
                hasil = Integer.toBinaryString(i);

            }else if(pilihan2.getSelectedItem().equals("Decimal")){
                i = Integer.parseInt(input.getText(),16);
                hasil = Integer.toString(i);

            }else if(pilihan2.getSelectedItem().equals("Hexadecimal")){
                a = (input.getText());
                hasil = a;

            }else if(pilihan2.getSelectedItem().equals("Octal")){
                i = Integer.parseInt(input.getText(),16);
                hasil = Integer.toOctalString(i);
            }

        }else if(pilihan1.getSelectedItem().equals("Octal")){

            if(pilihan2.getSelectedItem().equals("Binary")){
                i = Integer.parseInt(input.getText(),8);
                hasil = Integer.toBinaryString(i);

            }else if(pilihan2.getSelectedItem().equals("Decimal")){
                i = Integer.parseInt(input.getText(),8);
                hasil = String.format("%d",i);

            }else if(pilihan2.getSelectedItem().equals("Hexadecimal")){
                i = Integer.parseInt(input.getText(),8);
                hasil = Integer.toHexString(i);

            }else if(pilihan2.getSelectedItem().equals("Octal")){
                a = (input.getText());
                hasil = a;
            }

        }

        output.setText(hasil +  " ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(numeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(numeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(numeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(numeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new numeral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField output;
    private javax.swing.JComboBox<String> pilihan1;
    private javax.swing.JComboBox<String> pilihan2;
    // End of variables declaration//GEN-END:variables
}
