/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convertunits;

/**
 *
 * @author Smktelkom
 */
public class temperature extends javax.swing.JFrame {

    /**
     * Creates new form t
     */
    public temperature() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pilihan1 = new javax.swing.JComboBox<>();
        input = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pilihan2 = new javax.swing.JComboBox<>();
        output = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(244, 192, 66));
        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(122, 96, 33));
        jLabel2.setText("Temperature");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(140, 20, 170, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 420, 70);

        pilihan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));
        getContentPane().add(pilihan1);
        pilihan1.setBounds(20, 90, 110, 30);
        getContentPane().add(input);
        input.setBounds(20, 110, 110, 40);

        jPanel1.setBackground(new java.awt.Color(253, 89, 85));
        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/D:/Make it FUN/XI/PBO/SM2/small.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 120, 110, 40);

        jButton2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/D:/Make it FUN/XI/PBO/SM2/ba.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(110, 170, 110, 40);

        pilihan2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));
        jPanel1.add(pilihan2);
        pilihan2.setBounds(200, 20, 110, 30);

        output.setEditable(false);
        jPanel1.add(output);
        output.setBounds(200, 40, 110, 40);

        jLabel4.setFont(new java.awt.Font("Arrow Crafter", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("-------^");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 40, 50, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 70, 310, 230);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/D:/Make it FUN/XI/PBO/SM2/mer.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 70, 120, 230);

        setSize(new java.awt.Dimension(436, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String atas =pilihan1.getSelectedItem().toString();
        String bawah=pilihan2.getSelectedItem().toString();
        double Input = Double.parseDouble(input.getText()) ;
        double Hasil;
        
        //CELCIUS//
        if (pilihan1.getSelectedItem()=="Celcius" && pilihan2.getSelectedItem()=="Celcius"){
            Hasil=Input;
        output.setText(String.valueOf(Input));}
        
        if(pilihan1.getSelectedItem()=="Celcius" && pilihan2.getSelectedItem()=="Reamur"){
        Hasil=Input*4/5;
        output.setText(String.valueOf(Hasil));}
        
        if(pilihan1.getSelectedItem()=="Celcius" && pilihan2.getSelectedItem()=="Fahrenheit"){
        Hasil=Input*9/5+32;
        output.setText(String.valueOf(Hasil));}
        
        if(pilihan1.getSelectedItem()=="Celcius" && pilihan2.getSelectedItem()=="Kelvin"){
        Hasil=Input+273;
        output.setText(String.valueOf(Hasil));}
        //CELCIUS//
        
    //Fahrenheit//
        if(pilihan1.getSelectedItem()=="Fahrenheit" && pilihan2.getSelectedItem()=="Fahrenheit"){
        Hasil=Input;
        output.setText(String.valueOf(Hasil));}
        
        if(pilihan1.getSelectedItem()=="Fahrenheit" && pilihan2.getSelectedItem()=="Celcius"){
        Hasil=(Input-32)*5/9;
        output.setText(String.valueOf(Hasil));}
        
        if(pilihan1.getSelectedItem()=="Fahrenheit" && pilihan2.getSelectedItem()=="Kelvin"){
        Hasil=(Input-32)/1.8000+273.15;
        output.setText(String.valueOf(Hasil));}
        
        if(pilihan1.getSelectedItem()=="Fahrenheit" && pilihan2.getSelectedItem()=="Reamur"){
        Hasil=(Input-32)*4/9;
        output.setText(String.valueOf(Hasil));}
    //Fahrenheit//
    
        //REAMUR//
        if(pilihan1.getSelectedItem()=="Reamur" && pilihan2.getSelectedItem()=="Reamur"){
        Hasil=Input;
        output.setText(String.valueOf(Hasil));}
        
        if(pilihan1.getSelectedItem()=="Reamur" && pilihan2.getSelectedItem()=="Celcius"){
        Hasil=Input*5/4;
        output.setText(String.valueOf(Hasil));}
        
        if(pilihan1.getSelectedItem()=="Reamur" && pilihan2.getSelectedItem()=="Fahrenheit"){
        Hasil=(Input*9/4)+32;
        output.setText(String.valueOf(Hasil));}
        
        if(pilihan1.getSelectedItem()=="Reamur" && pilihan2.getSelectedItem()=="Kelvin"){
        Hasil=(Input/4*5)+273.15;
        output.setText(String.valueOf(Hasil));}
        //REAMUR//
        
    //Kelvin//
        if(pilihan1.getSelectedItem()=="Kelvin" && pilihan2.getSelectedItem()=="Kelvin"){
        Hasil=Input;
        output.setText(String.valueOf(Hasil));}
        
        if(pilihan1.getSelectedItem()=="Kelvin" && pilihan2.getSelectedItem()=="Celcius"){
        Hasil=Input-273.15;
        output.setText(String.valueOf(Hasil));}
        
        if(pilihan1.getSelectedItem()=="Kelvin" && pilihan2.getSelectedItem()=="Reamur"){
        Hasil=(Input-273.15)/5*4;
        output.setText(String.valueOf(Hasil));}
        
        if(pilihan1.getSelectedItem()=="Kelvin" && pilihan2.getSelectedItem()=="Fahrenheit"){
        Hasil=((Input-273.15)/5*9)+32;
        output.setText(String.valueOf(Hasil));}
    //Kelvin//
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new temperature().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField output;
    private javax.swing.JComboBox<String> pilihan1;
    private javax.swing.JComboBox<String> pilihan2;
    // End of variables declaration//GEN-END:variables
}
